name: deploy to vercel website
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test

# #     - name: Run the tests and generate coverage report
# #       run: npm test -- --coverage
      
#     - name: Build
#       run: npm run build

    - uses: amondnet/vercel-action@v20 #deploy
      with:
          vercel-token: 6BYMF6lfiyBkbncEhTccZYdp # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          # vercel-args: '--prod' #Optional
          vercel-org-id: 0OYYiGKCLlzbBL06WTKRLWC0  #Required
          vercel-project-id: prj_ac6vpw3ZJ6Li2paiTZafxVJyW9Q5 #Required 
          working-directory: ../../frontend/
