name: project-coinbase
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: 6BYMF6lfiyBkbncEhTccZYdp # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: 0OYYiGKCLlzbBL06WTKRLWC0  #Required
          vercel-project-id: prj_ac6vpw3ZJ6Li2paiTZafxVJyW9Q5 #Required 
          working-directory: ./frontend/
